### ISSUE TITLE
`node-pre-gyp install --fallback-to-build` fails (Win8 x64, node 5.1, npm 3.4)

### ISSUE THREAD

**Issue by aziraphale** [ForbesLindesay/thread-sleep#11]
Having upgraded my WIndows 8 x64 dev box to use Node 5.1.0 and npm 3.4.0, attempting to `npm install` everything reliably results in thread-sleep@1.0.4 failing to build:

```
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Andrew\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v5.1.0
npm ERR! npm  v3.4.0
npm ERR! code ELIFECYCLE

npm ERR! thread-sleep@1.0.4 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the thread-sleep@1.0.4 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the thread-sleep package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls thread-sleep
npm ERR! There is likely additional logging output above.
```

Earlier in the console output I also had this appear:

```
> thread-sleep@1.0.4 install C:\www\wren\node_modules\thread-sleep
> node-pre-gyp install --fallback-to-build


C:\www\wren\node_modules\thread-sleep>if not defined npm_config_node_gyp (node "C:\Users\Andrew\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node  clean )

C:\www\wren\node_modules\thread-sleep>if not defined npm_config_node_gyp (node "C:\Users\Andrew\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build --module=C:\www\wren\node_modules\thread-sleep\lib\binding\Release\node-v47-win32-x64\thread_sleep.node --module_name=thread_sleep --module_path=C:\www\wren\node_modules\thread-sleep\lib\binding\Release\node-v47-win32-x64 ) else (node  configure --fallback-to-build --module=C:\www\wren\node_modules\thread-sleep\lib\binding\Release\node-v47-win32-x64\thread_sleep.node --module_name=thread_sleep --module_path=C:\www\wren\node_modules\thread-sleep\lib\binding\Release\node-v47-win32-x64 )
gyp ERR! configure error
gyp ERR! stack Error: Command failed: python -c import platform; print(platform.python_version());
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:213:12)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:818:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:319:11)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at Socket.emit (events.js:169:7)
gyp ERR! stack     at Pipe._onclose (net.js:469:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Andrew\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\www\\wren\\node_modules\\thread-sleep\\lib\\binding\\Release\\node-v47-win32-x64\\thread_sleep.node" "--module_name=thread_sleep" "--module_path=C:\\www\\wren\\node_modules\\thread-sleep\\lib\\binding\\Release\\node-v47-win32-x64"
gyp ERR! cwd C:\www\wren\node_modules\thread-sleep
gyp ERR! node -v v5.1.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\www\wren\node_modules\thread-sleep\lib\binding\Release\node-v47-win32-x64\thread_sleep.node --module_name=thread_sleep --module_path=C:\www\wren\node_modules\thread-sleep\lib\binding\Release\node-v47-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\www\wren\node_modules\thread-sleep\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:818:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 6.3.9600
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\www\\wren\\node_modules\\thread-sleep\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\www\wren\node_modules\thread-sleep
node-pre-gyp ERR! node -v v5.1.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.9
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\www\wren\node_modules\thread-sleep\lib\binding\Release\node-v47-win32-x64\thread_sleep.node --module_name=thread_sleep --module_path=C:\www\wren\node_modules\thread-sleep\lib\binding\Release\node-v47-win32-x64' (1)
wren-framework@0.0.2 C:\www\wren
```

I've also attached the npm-debug.log file that was generated: [npm-debug.txt](https://github.com/ForbesLindesay/thread-sleep/files/38122/npm-debug.txt)

Any ideas? I'm embarrassingly ignorant when it comes to much of node/npm! :(

Thanks :)

**Comment by aziraphale** [comment]
I've just confirmed that downgrading to node 4.2.2 (leaving npm at 3.4.0) fixes this, with thread-sleep compiling/installing quite happily:

```
> thread-sleep@1.0.4 install C:\www\wren\node_modules\thread-sleep
> node-pre-gyp install --fallback-to-build

[thread-sleep] Success: "C:\www\wren\node_modules\thread-sleep\lib\binding\Release\node-v46-win32-x64\thread_sleep.node" is installed via remote
```

**Comment by knstntndmdnkv** [comment]
Ubuntu 14.04.3 \ node v0.12.10 and the same problem.

> npm install thread-sleep
> npm WARN package.json @ No repository field.
> npm WARN package.json @ No license field.
> /
> 
> > thread-sleep@1.0.4 install /var/www/node_modules/thread-sleep
> > node-pre-gyp install --fallback-to-build
> 
> sh: 1: node-pre-gyp: Permission denied
> npm ERR! Linux 3.13.0-55-generic
> npm ERR! argv "node" "/usr/local/bin/npm" "install" "thread-sleep"
> npm ERR! node v0.12.10
> npm ERR! npm  v2.13.0
> npm ERR! code ELIFECYCLE
> 
> npm ERR! thread-sleep@1.0.4 install: `node-pre-gyp install --fallback-to-build`
> npm ERR! Exit status 126
> npm ERR!
> npm ERR! Failed at the thread-sleep@1.0.4 install script 'node-pre-gyp install --fallback-to-build'.
> npm ERR! This is most likely a problem with the thread-sleep package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-pre-gyp install --fallback-to-build
> npm ERR! You can get their info via:
> npm ERR!     npm owner ls thread-sleep
> npm ERR! There is likely additional logging output above.
> npm ERR! Linux 3.13.0-55-generic
> npm ERR! argv "node" "/usr/local/bin/npm" "install" "thread-sleep"
> npm ERR! node v0.12.10
> npm ERR! npm  v2.13.0
> npm ERR! path npm-debug.log.c4f8d603de0a51ddef3577b16c247b36
> npm ERR! code ETXTBSY
> npm ERR! errno -26
> 
> npm ERR! ETXTBSY, rename 'npm-debug.log.c4f8d603de0a51ddef3577b16c247b36'
> npm ERR!
> npm ERR! If you need help, you may report this error at:
> npm ERR!     https://github.com/npm/npm/issues
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /var/www/npm-debug.log

**Comment by pcoutin** [comment]
Ubuntu 14.04.4 LTS x86_64 and the same problem

```
module.js:340
throw err;
^
Error: Cannot find module '../'
at Function.Module._resolveFilename (module.js:338:15)
at Function.Module._load (module.js:280:25)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object.<anonymous>
(/home/pcoutin/.meteor/packages/fourseven_scss/.3.4.3.n6zen7++os.linux.x86_64+web.browser+web.cordova/plugin.compileScssBatch.os.linux.x86_64/npm/node_modules/meteor/compileScssBatch/node_modules/.temp-11hsc6/node_modules/node-sass/node_modules/cross-spawn/node_modules/spawn-sync/node_modules/try-thread-sleep/node_modules/thread-sleep/node_modules/.bin/node-pre-gyp:15:20)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Function.Module.runMain (module.js:497:10)

npm ERR! Linux 3.16.0-77-generic
npm ERR! argv "node" "/home/pcoutin/.meteor/packages/meteor-tool/.1.3.5_1.q7oj75++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm" "rebuild" "--no-bin-links" "--update-binary"
npm ERR! node v0.10.46
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! thread-sleep@1.0.4 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the thread-sleep@1.0.4 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the thread-sleep package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs thread-sleep
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls thread-sleep
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!
```

**Comment by mtwalsh** [comment]
I've hit this same problem upgrading a Meteor project to 1.4.0.1 (with fourseven:scss), on both Mac OSX El Capitan and Windows 10.

**Comment by mtwalsh** [comment]
Actually, I was able to resolve it by removing the `fourseven:scss` package, running `meteor update` to 1.4.0.1 and then adding it back.

**Comment by BryanCrotaz** [comment]
Windows Node 6.9.1, same problem

**Comment by ForbesLindesay** [comment]
This module no longer has any native dependencies.

**Comment by BryanCrotaz** [comment]
Yay! Only took three years 😜

**Comment by ForbesLindesay** [comment]
I'm slowly working through my backlog :)

**Comment by ForbesLindesay** [comment]
To be fair, the problem was actually fixed  29 Dec 2016, so it only took two months to fix, and three years to close the issue.
